# Generated by Django 2.2.14 on 2020-08-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post list'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='Posts',
        ),
    ]
